-- V15: Index existing knowledge documents with embeddings
-- This populates knowledge_document_embeddings table for vector search capability

-- Note: The actual embeddings will be generated by IndexKnowledgeDocumentUseCase
-- This migration ensures the table structure is ready and creates placeholders

-- First, ensure the knowledge_document_embeddings table has the right indexes
-- (should already exist from V12, but let's be defensive)
CREATE INDEX IF NOT EXISTS idx_knowledge_document_embeddings_document_id 
    ON knowledge_document_embeddings(document_id);

-- Ensure HNSW index exists for vector search performance
-- This will be populated when embeddings are generated
DROP INDEX IF EXISTS idx_knowledge_document_embeddings_vector;
CREATE INDEX idx_knowledge_document_embeddings_vector 
    ON knowledge_document_embeddings 
    USING hnsw (embedding vector_cosine_ops) 
    WITH (m = 16, ef_construction = 64);

-- Create a function to trigger document reindexing when content changes
CREATE OR REPLACE FUNCTION notify_knowledge_document_updated()
    RETURNS TRIGGER AS $$
BEGIN
    -- This will be picked up by application listeners for re-indexation
    -- For now, just log the change
    RAISE NOTICE 'Knowledge document % updated, should re-index embeddings', NEW.id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto-reindexing when documents are modified
DROP TRIGGER IF EXISTS trg_knowledge_document_updated ON knowledge_documents;
CREATE TRIGGER trg_knowledge_document_updated
    AFTER UPDATE OF content, title, active ON knowledge_documents
    FOR EACH ROW
    WHEN (OLD.content IS DISTINCT FROM NEW.content 
          OR OLD.title IS DISTINCT FROM NEW.title 
          OR OLD.active IS DISTINCT FROM NEW.active)
    EXECUTE FUNCTION notify_knowledge_document_updated();

-- The actual embedding generation will be handled by IndexKnowledgeDocumentUseCase
-- via Spring Boot application startup or admin endpoint